# Generated by Django 4.2.7 on 2024-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_name', models.CharField(max_length=50)),
                ('breakfast_picture', models.ImageField(upload_to='')),
                ('breakfast_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breakfast_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burger_name', models.CharField(max_length=50)),
                ('burger_picture', models.ImageField(upload_to='')),
                ('burger_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('burger_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_name', models.CharField(max_length=50)),
                ('dessert_picture', models.ImageField(upload_to='')),
                ('dessert_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_name', models.CharField(max_length=50)),
                ('dinner_picture', models.ImageField(upload_to='')),
                ('dinner_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks_name', models.CharField(max_length=50)),
                ('drinks_picture', models.ImageField(upload_to='')),
                ('drinks_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=50)),
                ('pizza_picture', models.ImageField(upload_to='')),
                ('pizza_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks_name', models.CharField(max_length=50)),
                ('snacks_picture', models.ImageField(upload_to='')),
                ('snacks_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
