# Generated by Django 5.0 on 2023-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks_name', models.CharField(max_length=50)),
                ('drinks_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
