# Generated by Django 5.0 on 2023-12-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drinks_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=5),
            preserve_default=False,
        ),
    ]
