# Generated by Django 5.0 on 2023-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0002_drink_drinks_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_name', models.CharField(max_length=50)),
                ('dessert_picture', models.ImageField(upload_to='')),
                ('dessert_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks_name', models.CharField(max_length=50)),
                ('snacks_picture', models.ImageField(upload_to='')),
                ('snacks_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
