# Generated by Django 5.0 on 2023-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0003_dessert_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_name', models.CharField(max_length=50)),
                ('breakfast_picture', models.ImageField(upload_to='')),
                ('breakfast_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burger_name', models.CharField(max_length=50)),
                ('burger_picture', models.ImageField(upload_to='')),
                ('burger_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_name', models.CharField(max_length=50)),
                ('dinner_picture', models.ImageField(upload_to='')),
                ('dinner_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=50)),
                ('pizza_picture', models.ImageField(upload_to='')),
                ('pizza_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
