# Generated by Django 5.0 on 2023-12-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0004_breakfast_burger_dinner_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='burger_description',
            field=models.CharField(default=250, max_length=250),
            preserve_default=False,
        ),
    ]
