# Generated by Django 5.0 on 2023-12-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0005_burger_burger_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='breakfast_description',
            field=models.CharField(default=250, max_length=250),
            preserve_default=False,
        ),
    ]
