# Generated by Django 4.2.7 on 2024-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('time', models.TimeField(max_length=50)),
                ('No_of_guest', models.CharField(max_length=50)),
            ],
        ),
    ]
