# Generated by Django 4.2.7 on 2024-01-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0010_order_food_name_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.breakfast')),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.burger')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.customer')),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.dessert')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.dinner')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.drink')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.pizza')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.snack')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
