# Generated by Django 4.2.7 on 2024-01-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0011_food_item_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item',
            name='customer',
        ),
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.customer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_orders.food_item')),
            ],
        ),
    ]
